// AUTO-GENERATED by inshellisense/scripts/gen-claude-spec.mjs
// Source: https://code.claude.com/docs/en/cli-reference.md
// 編集禁止 — 再生成は scripts/gen-claude-spec.mjs を実行する。

const spec = {
  "name": "claude",
  "description": "Claude Code CLI",
  "subcommands": [
    {
      "name": "update",
      "description": "Update to latest version"
    },
    {
      "name": "install",
      "description": "Install or reinstall the native binary. Accepts a version like 2.1.118, or stable or latest. See Install a specific version",
      "args": {
        "name": "version",
        "isOptional": true
      }
    },
    {
      "name": "auth",
      "description": "auth subcommand group",
      "subcommands": [
        {
          "name": "login",
          "description": "Sign in to your Anthropic account. Use --email to pre-fill your email address, --sso to force SSO authentication, and --console to sign in with Anthropic Console for API usage billing instead of a Claude subscription"
        },
        {
          "name": "logout",
          "description": "Log out from your Anthropic account"
        },
        {
          "name": "status",
          "description": "Show authentication status as JSON. Use --text for human-readable output. Exits with code 0 if logged in, 1 if not"
        }
      ]
    },
    {
      "name": "agents",
      "description": "Open agent view to monitor and dispatch parallel background sessions. Use --cwd <path> to show only sessions started under that directory, or --json to print live sessions as a JSON array for scripting."
    },
    {
      "name": "attach",
      "description": "Attach to a background session in this terminal",
      "args": {
        "name": "id"
      }
    },
    {
      "name": "auto-mode",
      "description": "auto-mode subcommand group",
      "subcommands": [
        {
          "name": "defaults",
          "description": "Print the built-in auto mode classifier rules as JSON. Use claude auto-mode config to see your effective config with settings applied"
        }
      ]
    },
    {
      "name": "daemon",
      "description": "daemon subcommand group",
      "subcommands": [
        {
          "name": "status",
          "description": "Print the background-session supervisor's state, version, socket directory, and worker count for diagnostics. Exits 1 if the supervisor isn't running"
        },
        {
          "name": "stop",
          "description": "Stop the background-session supervisor and the sessions it hosts. Pass --keep-workers to leave background sessions running so the next supervisor reconnects to them. --any confirms stopping an on-demand supervisor, which is the default."
        }
      ]
    },
    {
      "name": "logs",
      "description": "Print recent output from a background session",
      "args": {
        "name": "id"
      }
    },
    {
      "name": "mcp",
      "description": "Configure Model Context Protocol (MCP) servers"
    },
    {
      "name": "plugin",
      "description": "Manage Claude Code plugins. Alias: claude plugins. See plugin reference for subcommands"
    },
    {
      "name": "project",
      "description": "project subcommand group",
      "subcommands": [
        {
          "name": "purge",
          "description": "Delete all local Claude Code state for a project: transcripts, task lists, debug logs, file-edit history, prompt history lines, and the project's entry in ~/.claude.json. Omit [path] to pick from an interactive list.",
          "args": {
            "name": "path",
            "isOptional": true
          }
        }
      ]
    },
    {
      "name": "remote-control",
      "description": "Start a Remote Control server to control Claude Code from Claude.ai or the Claude app. Runs in server mode (no local interactive session). See Server mode flags"
    },
    {
      "name": "respawn",
      "description": "Restart a background session, running or stopped, with its conversation intact. Use --all to restart every running session, e.g. to pick up an updated Claude Code binary",
      "args": {
        "name": "id"
      }
    },
    {
      "name": "rm",
      "description": "Remove a background session from the list. The conversation transcript stays on your local machine, available through claude --resume",
      "args": {
        "name": "id"
      }
    },
    {
      "name": "setup-token",
      "description": "Generate a long-lived OAuth token for CI and scripts. Prints the token to the terminal without saving it. Requires a Claude subscription. See Generate a long-lived token"
    },
    {
      "name": "stop",
      "description": "Stop a background session. Also accepts claude kill",
      "args": {
        "name": "id"
      }
    },
    {
      "name": "ultrareview",
      "description": "Run ultrareview non-interactively. Prints findings to stdout and exits 0 on success or 1 on failure. Use --json for the raw payload and --timeout <minutes> to override the 30-minute default",
      "args": {
        "name": "target",
        "isOptional": true
      }
    }
  ],
  "options": [
    {
      "name": "--add-dir",
      "description": "Add additional working directories for Claude to read and edit files. Grants file access; most .claude/ configuration is not discovered from these directories. Validates each path exists as a directory.",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--agent",
      "description": "Specify an agent for the current session (overrides the agent setting)",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--agents",
      "description": "Define custom subagents dynamically via JSON. Uses the same field names as subagent frontmatter, plus a prompt field for the agent's instructions",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--allow-dangerously-skip-permissions",
      "description": "Add bypassPermissions to the Shift+Tab mode cycle without starting in it. Lets you begin in a different mode like plan and switch to bypassPermissions later. See permission modes"
    },
    {
      "name": "--allowedTools",
      "description": "Tools that execute without prompting for permission. See permission rule syntax for pattern matching. To restrict which tools are available, use --tools instead",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--append-system-prompt",
      "description": "Append custom text to the end of the default system prompt",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--append-system-prompt-file",
      "description": "Load additional system prompt text from a file and append to the default prompt",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--bare",
      "description": "Minimal mode: skip auto-discovery of hooks, skills, plugins, MCP servers, auto memory, and CLAUDE.md so scripted calls start faster. Claude has access to Bash, file read, and file edit tools. Sets CLAUDE_CODE_SIMPLE. See bare mode"
    },
    {
      "name": "--betas",
      "description": "Beta headers to include in API requests (API key users only)",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--bg",
      "description": "Start the session as a background agent and return immediately. Prints the session ID and management commands. Combine with --exec to run a shell command as a background job instead of a Claude session, or with --agent to run a specific sub…",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--channels",
      "description": "(Research preview) MCP servers whose channel notifications Claude should listen for in this session. Space-separated list of plugin:<name>@<marketplace> entries. Requires Claude.ai authentication",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--chrome",
      "description": "Enable Chrome browser integration for web automation and testing"
    },
    {
      "name": [
        "--continue",
        "-c"
      ],
      "description": "Load the most recent conversation in the current directory. Includes sessions that added this directory with /add-dir"
    },
    {
      "name": "--dangerously-load-development-channels",
      "description": "Enable channels that are not on the approved allowlist, for local development. Accepts plugin:<name>@<marketplace> and server:<name> entries. Prompts for confirmation",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--dangerously-skip-permissions",
      "description": "Skip permission prompts. Equivalent to --permission-mode bypassPermissions. See permission modes for what this does and does not skip"
    },
    {
      "name": "--debug",
      "description": "Enable debug mode with optional category filtering (for example, \"api,hooks\" or \"!statsig,!file\")",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--debug-file",
      "description": "Write debug logs to a specific file path. Implicitly enables debug mode. Takes precedence over CLAUDE_CODE_DEBUG_LOGS_DIR",
      "args": {
        "name": "path"
      }
    },
    {
      "name": "--disable-slash-commands",
      "description": "Disable all skills and commands for this session"
    },
    {
      "name": "--disallowedTools",
      "description": "Deny rules. A bare tool name removes that tool from the model's context. A scoped rule such as Bash(rm *) leaves the tool available and denies only matching calls",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--effort",
      "description": "Set the effort level for the current session. Options: low, medium, high, xhigh, max; available levels depend on the model. Overrides the effortLevel setting for this session and does not persist",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--exclude-dynamic-system-prompt-sections",
      "description": "Move per-machine sections from the system prompt (working directory, environment info, memory paths, git-repo flag) into the first user message. Improves prompt-cache reuse across different users and machines running the same task."
    },
    {
      "name": "--exec",
      "description": "Run a shell command as a PTY-backed background job instead of starting a Claude session. Use with --bg to launch from the shell",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--fallback-model",
      "description": "Enable automatic fallback to a specified model when the default model is overloaded or not available, for example a retired model. Takes effect in print mode (-p) and in background sessions, which run non-interactively;",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--fork-session",
      "description": "When resuming, create a new session ID instead of reusing the original (use with --resume or --continue)"
    },
    {
      "name": "--from-pr",
      "description": "Resume sessions linked to a specific pull request. Accepts a PR number, a GitHub or GitHub Enterprise PR URL, a GitLab merge request URL, or a Bitbucket pull request URL.",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--ide",
      "description": "Automatically connect to IDE on startup if exactly one valid IDE is available"
    },
    {
      "name": "--init",
      "description": "Run Setup hooks with the init matcher before the session (print mode only)"
    },
    {
      "name": "--init-only",
      "description": "Run Setup and SessionStart hooks, then exit without starting a conversation"
    },
    {
      "name": "--include-hook-events",
      "description": "Include all hook lifecycle events in the output stream. Requires --output-format stream-json"
    },
    {
      "name": "--include-partial-messages",
      "description": "Include partial streaming events in output. Requires --print and --output-format stream-json"
    },
    {
      "name": "--input-format",
      "description": "Specify input format for print mode (options: text, stream-json)",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--json-schema",
      "description": "Get validated JSON output matching a JSON Schema after agent completes its workflow (print mode only, see structured outputs)",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--maintenance",
      "description": "Run Setup hooks with the maintenance matcher before the session (print mode only)"
    },
    {
      "name": "--max-budget-usd",
      "description": "Maximum dollar amount to spend on API calls before stopping (print mode only)",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--max-turns",
      "description": "Limit the number of agentic turns (print mode only). Exits with an error when the limit is reached. No limit by default",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--mcp-config",
      "description": "Load MCP servers from JSON files or strings (space-separated)",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--model",
      "description": "Sets the model for the current session with an alias for the latest model (sonnet or opus) or a model's full name. Overrides the model setting and ANTHROPIC_MODEL",
      "args": {
        "name": "value"
      }
    },
    {
      "name": [
        "--name",
        "-n"
      ],
      "description": "Set a display name for the session, shown in /resume and the terminal title. You can resume a named session with claude --resume <name>. /rename changes the name mid-session and also shows it on the prompt bar",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--no-chrome",
      "description": "Disable Chrome browser integration for this session"
    },
    {
      "name": "--no-session-persistence",
      "description": "Disable session persistence so sessions are not saved to disk and cannot be resumed. Print mode only. The CLAUDE_CODE_SKIP_PROMPT_HISTORY environment variable does the same in any mode"
    },
    {
      "name": "--output-format",
      "description": "Specify output format for print mode (options: text, json, stream-json)",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--permission-mode",
      "description": "Begin in a specified permission mode. Accepts default, acceptEdits, plan, auto, dontAsk, or bypassPermissions. Overrides defaultMode from settings files",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--permission-prompt-tool",
      "description": "Specify an MCP tool to handle permission prompts in non-interactive mode",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--plugin-dir",
      "description": "Load a plugin from a directory or .zip archive for this session only. Each flag takes one path. Repeat the flag for multiple plugins: --plugin-dir A --plugin-dir B.zip",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--plugin-url",
      "description": "Fetch a plugin .zip archive from a URL for this session only. Repeat the flag for multiple plugins, or pass space-separated URLs in a single quoted value",
      "args": {
        "name": "value"
      }
    },
    {
      "name": [
        "--print",
        "-p"
      ],
      "description": "Print response without interactive mode (see Agent SDK documentation for programmatic usage details)"
    },
    {
      "name": "--prompt-suggestions",
      "description": "Emit a prompt_suggestion message after each turn with a predicted next user prompt. Requires --print, --output-format stream-json, and --verbose. See Prompt suggestions"
    },
    {
      "name": "--remote",
      "description": "Create a new web session on claude.ai with the provided task description",
      "args": {
        "name": "value"
      }
    },
    {
      "name": [
        "--remote-control",
        "--rc"
      ],
      "description": "Start an interactive session with Remote Control enabled so you can also control it from claude.ai or the Claude app. Optionally pass a name for the session",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--remote-control-session-name-prefix",
      "description": "Prefix for auto-generated Remote Control session names when no explicit name is set. Defaults to your machine's hostname, producing names like myhost-graceful-unicorn. Set CLAUDE_REMOTE_CONTROL_SESSION_NAME_PREFIX for the same effect",
      "args": {
        "name": "prefix"
      }
    },
    {
      "name": "--replay-user-messages",
      "description": "Re-emit user messages from stdin back on stdout for acknowledgment. Requires --input-format stream-json and --output-format stream-json"
    },
    {
      "name": [
        "--resume",
        "-r"
      ],
      "description": "Resume a specific session by ID or name, or show an interactive picker to choose a session. Includes sessions that added this directory with /add-dir. As of v2.1.144, background sessions appear in the picker marked with bg",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--session-id",
      "description": "Use a specific session ID for the conversation (must be a valid UUID)",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--setting-sources",
      "description": "Comma-separated list of setting sources to load (user, project, local)",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--settings",
      "description": "Path to a settings JSON file or an inline JSON string. Values you set here override the same keys in your settings.json files for this session. Keys you omit keep their file-based values. See settings precedence",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--strict-mcp-config",
      "description": "Only use MCP servers from --mcp-config, ignoring all other MCP configurations"
    },
    {
      "name": "--system-prompt",
      "description": "Replace the entire system prompt with custom text",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--system-prompt-file",
      "description": "Load system prompt from a file, replacing the default prompt",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--teleport",
      "description": "Resume a web session in your local terminal"
    },
    {
      "name": "--teammate-mode",
      "description": "Set how agent team teammates display: auto (default), in-process, or tmux. Overrides the teammateMode setting for this session. See Choose a display mode",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--tmux",
      "description": "Create a tmux session for the worktree. Requires --worktree. Uses iTerm2 native panes when available; pass --tmux=classic for traditional tmux"
    },
    {
      "name": "--tools",
      "description": "Restrict which built-in tools Claude can use. Use \"\" to disable all, \"default\" for all, or tool names like \"Bash,Edit,Read\"",
      "args": {
        "name": "value"
      }
    },
    {
      "name": "--verbose",
      "description": "Enable verbose logging, shows full turn-by-turn output. Overrides the viewMode setting for this session"
    },
    {
      "name": [
        "--version",
        "-v"
      ],
      "description": "Output the version number"
    },
    {
      "name": [
        "--worktree",
        "-w"
      ],
      "description": "Start Claude in an isolated git worktree at <repo>/.claude/worktrees/<name>. If no name is given, one is auto-generated. Pass #<number> or a GitHub pull request URL to fetch that PR from origin and branch the worktree from it",
      "args": {
        "name": "value"
      }
    }
  ]
};

export default spec;
